---
extends: "default"

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: false
  indentation: {spaces: 2, indent-sequences: true}
  # do not obsess over comment formatting
  comments-indentation: false
  comments:
    require-starting-space: false
  quoted-strings: {quote-type: "any"}

ignore: |
  .rubocop.yml
