mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/vcsrepo'
mod 'puppet/ssh_keygen'
mod 'puppetlabs/ntp'
mod 'aboe/chrony'
mod 'puppetlabs-java'
mod 'puppet-archive'
mod 'crayfishx-firewalld'
mod 'puppet-yum'
mod 'puppet-virtualbox'
mod 'ghoneycutt-ssh'
mod 'ts_sal',
	:git => 'https://github.com/lsst/ts_sal.git'
mod 'ts_xml',
	:git => 'https://github.com/lsst/ts_xml.git'
mod 'puppetlabs-inifile'
mod 'datacentred-telegraf'
mod 'stahnma-epel'
mod 'golja-influxdb'
mod 'puppet-grafana'
mod 'graylog-graylog'
mod 'puppet-mongodb'
mod 'richardc-datacat'
mod 'elastic-elastic_stack'
mod 'elastic-elasticsearch'
mod 'puppet-rsyslog'
mod 'puppet-dhcp'
mod 'ccs',
	:git => 'https://github.com/LSST-IT/puppet-ccs.git'
mod 'efd',
	:git => 'https://github.com/LSST-IT/puppet-efd.git'
mod 'headerservice',
	:git => 'https://github.com/LSST-IT/puppet-headerservice.git'