---
ipa::ipa_master_fqdn: "ipa1.ls.lsst.org"
rsyslog::feature_packages:
  - "rsyslog-openssl"
rsyslog::config::actions:
  fluentbit_dev:
    type: "omfwd"
    facility: "*.*"
    config:
      target: "rsyslog.fluent.ayekan.dev.lsst.org"
      port: 5140
      protocol: "tcp"
      StreamDriver: "ossl"
      StreamDriverMode: "1"
      StreamDriverAuthMode: "anon"
  fluentbit_ruka:
    type: "omfwd"
    facility: "*.*"
    config:
      target: "rsyslog.fluent.ruka.dev.lsst.org"
      port: 5140
      protocol: "tcp"
      StreamDriver: "ossl"
      StreamDriverMode: "1"
      StreamDriverAuthMode: "anon"
# The following keys are shared between the `dhcp` and `resolv_conf` classes:
# - dhcp::dnsdomain
# - dhcp::nameservers
# - dhcp::ntpservers
#
# @see site/ls/role/foreman.yaml

# resolv.conf allows for a maximum of 6 search domains with a max length of 256
# characters.
# @see man 5 resolv.conf
dhcp::dnsdomain: &dnsdomains
  - "dev.lsst.org"
  - "ls.lsst.org"
  - "lsst.org"
# resolv.conf allows for a maximum of 3 nameservers
# @see man 5 resolv.conf
dhcp::nameservers: &nameservers
  - "139.229.134.53"  # dns1.dev.lsst.org
  - "139.229.134.54"  # dns2.dev.lsst.org
  - "139.229.134.55"  # dns3.dev.lsst.org
dhcp::ntpservers: &ntpservers
  - "ntp.shoa.cl"
  - "ntp.cp.lsst.org"
  - "1.cl.pool.ntp.org"
  - "1.south-america.pool.ntp.org"

chrony::servers: *ntpservers
ntp::servers: *ntpservers
resolv_conf::nameservers: *nameservers
resolv_conf::searchpath: *dnsdomains

accounts::user_list:
  root:
    purge_sshkeys: true
    sshkeys:
      # foreman-proxy
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIAmA8aQ9Qf8ok+zPUSwFWfEgNxUW1RptUhZE9/9PFGzhAi7XMnt6qaSFINlLxiECUXKeK3iwHI3rLxMsJpcGRGkkL9GGpUYNgyDVZt82AFN2rt7nvuYqm9M7M4Q6NeLlMEGUf9iSnzE/IpT4459iOiKdaB3SifuXWjJeUSOoNACugJcQCZm4nQGo9ZUVJcbhYael++pcobApctOOFjlaVi6s+iB4qdidMJ9CUEyQ8HBSDomBnj2dZ5QB/bDHUW1OKo/i+LbMdF1HrnEcI9AkSHfkW+OP7L5mkmRJBNsK5R6YzIb41LHCvO1Fvoinb71JkWD5ElzTLY5e7YkjRXkQV foreman-proxy@foreman.dev.lsst.org"

letsencrypt::server: "https://acme-staging.api.letsencrypt.org/directory"  # testing url
profile::core::common::disable_ipv6: true

profile::core::firewall::firewall:
  "100 accept node_exporter":
    proto: "tcp"
    state: "NEW"
    ipset: "ayekan src"
    dport: "9100"
    jump: "accept"
  "101 accept node_exporter":
    proto: "tcp"
    state: "NEW"
    ipset: "dev src"  # allow ruka to access node_exporter
    dport: "9100"
    jump: "accept"

profile::core::docker::version: "24.0.9"

s3daemon::instances:
  ruka:
    s3_endpoint_url: "https://s3.ruka.dev.lsst.org"
    port: 15570
