# This file is managed by Puppet; changes may be overwritten.
/opt/tomcat/catalina_base/logs/catalina.out {
    su tomcat tomcat
    copytruncate
    notifempty
    missingok
    compress
    weekly
    rotate 4
    dateext
}
